version: "3.4"
services:
  api-service:
    container_name: api-service
    # network_mode: "host"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ticketing-network

  db:
    container_name: db
    # network_mode: "host"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "12345689@a"
      ACCEPT_EULA: "Y"
    networks:
      - ticketing-network

networks:
  ticketing-network:
    name: ticketing-net
